More debug.

diff --git a/etc/service/postfix/run b/etc/service/postfix/run
--- a/etc/service/postfix/run
+++ b/etc/service/postfix/run
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR
+
 postconf -e maillog_file=/dev/stdout
 
 if [ "$MAILNAME" ]; then
@@ -32,27 +34,27 @@ fi
 if [ -f /etc/alpine-release ]; then
   output=$(/usr/sbin/postfix -c /etc/postfix start 2>&1)
   if [ $? -ne 0 ]; then
-    echo "init start failed"
-    echo "$output"
+    echo "init start failed" >&2
+    echo "$output" >&2
     exit "$?"
   fi
   output=$(/usr/sbin/postfix -c /etc/postfix abort 2>&1)
   if [ $? -ne 0 ]; then
-    echo "init abort failed"
-    echo "$output"
+    echo "init abort failed" >&2
+    echo "$output" >&2
     exit "$?"
   fi
 else
   output=$(/etc/init.d/postfix start 2>&1)
   if [ $? -ne 0 ]; then
-    echo "init start failed"
-    echo "$output"
+    echo "init start failed" >&2
+    echo "$output" >&2
     exit "$?"
   fi
   output=$(/etc/init.d/postfix abort 2>&1)
   if [ $? -ne 0 ]; then
-    echo "init abort failed"
-    echo "$output"
+    echo "init abort failed" >&2
+    echo "$output" >&2
     exit "$?"
   fi
 fi
